{
    "type": "bundle",
    "id": "bundle--d64f572d-3a7d-4d89-9543-1be78d6b7960",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--51219a40-29f8-4270-9a2e-609db6e94fb3",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2022-08-18T00:57:46.597399Z",
            "modified": "2022-08-18T00:57:46.597399Z",
            "name": "CVE-1999-0846",
            "description": "Denial of service in MDaemon 2.7 via a large number of connection attempts.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-1999-0846"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}