{
    "type": "bundle",
    "id": "bundle--4bf8ffd3-0ae0-44e1-bcaf-9b1d42d1537a",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--8ef82c35-1bf0-45d8-a28a-b274261c18d8",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2022-06-09T00:49:22.035338Z",
            "modified": "2022-06-09T00:49:22.035338Z",
            "name": "CVE-2022-31313",
            "description": "api-res-py package in PyPI 0.1 is vulnerable to a code execution backdoor in the request package.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2022-31313"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}