{
    "type": "bundle",
    "id": "bundle--6db6e198-b60b-42ca-80bd-8d96404b4d62",
    "objects": [
        {
            "type": "vulnerability",
            "spec_version": "2.1",
            "id": "vulnerability--f0104f9a-e708-4f0c-af29-d127c5830c50",
            "created_by_ref": "identity--8ce3f695-d5a4-4dc8-9e93-a65af453a31a",
            "created": "2021-05-21T00:29:12.328019Z",
            "modified": "2021-05-21T00:29:12.328019Z",
            "name": "CVE-2021-22409",
            "description": "There is a denial of service vulnerability in some versions of ManageOne. There is a logic error in the implementation of a function of a module. When the service pressure is heavy, there is a low probability that an exception may occur. Successful exploit may cause some services abnormal.",
            "external_references": [
                {
                    "source_name": "cve",
                    "external_id": "CVE-2021-22409"
                }
            ],
            "object_marking_refs": [
                "marking-definition--62fd3f9b-15f3-4ebc-802c-91fce9536bcf"
            ]
        }
    ]
}